$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: joon-grpc2
environment:
  name: grpc
  version: 3
  # This needs to be workspace ACR
  image: 6f03fe9ab75b4d839b18fd0588c370d0.azurecr.io/joongrpc:2
  inference_config:
    liveness_route:
      port: 5001
      path: /healthz
    readiness_route:
      port: 5001
      path: /healthz
    scoring_route:
      port: 5000
      path: /
instance_type: Standard_F2s_v2
instance_count: 1
request_settings:
  request_timeout_ms: 5000
