// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: scorer.proto

package scorerpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on InferenceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned. When asked to return all errors, validation continues
// after first violation, and the result is a list of violation errors wrapped
// in InferenceRequestMultiError, or nil if none found. Otherwise, only the
// first error is returned, if any.
func (m *InferenceRequest) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Prompt

	if len(errors) > 0 {
		return InferenceRequestMultiError(errors)
	}
	return nil
}

// InferenceRequestMultiError is an error wrapping multiple validation errors
// returned by InferenceRequest.Validate(true) if the designated constraints
// aren't met.
type InferenceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InferenceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InferenceRequestMultiError) AllErrors() []error { return m }

// InferenceRequestValidationError is the validation error returned by
// InferenceRequest.Validate if the designated constraints aren't met.
type InferenceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InferenceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InferenceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InferenceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InferenceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InferenceRequestValidationError) ErrorName() string { return "InferenceRequestValidationError" }

// Error satisfies the builtin error interface
func (e InferenceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInferenceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InferenceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InferenceRequestValidationError{}

// Validate checks the field values on InferenceResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned. When asked to return all errors, validation continues
// after first violation, and the result is a list of violation errors wrapped
// in InferenceResponseMultiError, or nil if none found. Otherwise, only the
// first error is returned, if any.
func (m *InferenceResponse) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Result

	if len(errors) > 0 {
		return InferenceResponseMultiError(errors)
	}
	return nil
}

// InferenceResponseMultiError is an error wrapping multiple validation errors
// returned by InferenceResponse.Validate(true) if the designated constraints
// aren't met.
type InferenceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InferenceResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InferenceResponseMultiError) AllErrors() []error { return m }

// InferenceResponseValidationError is the validation error returned by
// InferenceResponse.Validate if the designated constraints aren't met.
type InferenceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InferenceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InferenceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InferenceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InferenceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InferenceResponseValidationError) ErrorName() string {
	return "InferenceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e InferenceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInferenceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InferenceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InferenceResponseValidationError{}
